"""Language-Detection-With-MultinomialNB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjhmKNEogG5CrVgLv_rVRwT3yrRxQNGH

**Language Detection With MultinomialNB**

In this project, i will try to detect the language of users text. I will use MultinomialNB model from sklearn. And i will use CountVectorizer method also from sklearn. Lets start with import libraries.
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.naive_bayes import MultinomialNB

# Created data frames. I just created a special Turkish data frame to see Turkish data.
df = pd.read_csv("text_language.csv")
#tr = df[df["language"] == "Turkish"]

#df.head()

#tr.head()

#df["language"].value_counts()

# Checked if there any missing observation
#df.isnull().sum()

"""**Modelling**"""

# Dependent and independent variables
x = np.array(df["Text"])
y = np.array(df["language"])

# Data divided into training and test
cv = CountVectorizer()
X = cv.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Model setup
model = MultinomialNB().fit(X_train, y_train)

# Models score
#model.score(X_test, y_test)

# Models accuracy
#acc = accuracy_score(model.predict(X_test), y_test)
#print(f"Accuracy: %{acc*100}")

# Example usage
#user_input = input("Type something: ")
#data = cv.transform([user_input]).toarray()
#output = model.predict(data)
#print(f"Detected language: {output}")